#!/bin/bash

declare -A datasets
datasets[1]='adult'
datasets[2]='bank_marketing'
datasets[3]='bean'
datasets[4]='compas'
datasets[5]='concrete'
datasets[6]='credit_card'
datasets[7]='diabetes'
datasets[8]='energy'
datasets[9]='flight_delays'
datasets[10]='german_credit'
datasets[11]='htru2'
datasets[12]='life'
datasets[13]='naval'
datasets[14]='no_show'
datasets[15]='obesity'
datasets[16]='power'
datasets[17]='protein'
datasets[18]='spambase'
datasets[19]='surgical'
datasets[20]='vaccine'
datasets[21]='wine'
datasets[22]='twitter'
