
o='jobs/logs/inf/'
t='lgb'

sbatch -a 1-21  -c 3  -t 1440 -p 'short' -o '${o}${t}_random-%a.out'     jobs/inf/runner.sh $t 'random'
sbatch -a 1-21  -c 3  -t 1440 -p 'short' -o '${o}${t}_target-%a.out'     jobs/inf/runner.sh $t 'target'
sbatch -a 1-21  -c 3  -t 1440 -p 'short' -o '${o}${t}_input_sim-%a.out'  jobs/inf/runner.sh $t 'input_sim'
sbatch -a 1-21  -c 3  -t 1440 -p 'short' -o '${o}${t}_leaf_sim-%a.out'   jobs/inf/runner.sh $t 'leaf_sim'
sbatch -a 1-21  -c 3  -t 1440 -p 'short' -o '${o}${t}_boostin-%a.out'    jobs/inf/runner.sh $t 'boostin'
sbatch -a 1-21  -c 3  -t 1440 -p 'short' -o '${o}${t}_leaf_infSP-%a.out' jobs/inf/runner.sh $t 'leaf_infSP'
sbatch -a 1-21  -c 9  -t 1440 -p 'short' -o '${o}${t}_trex-%a.out'       jobs/inf/runner.sh $t 'trex'
sbatch -a 1-21  -c 5  -t 1440 -p 'short' -o '${o}${t}_subsample-%a.out'  jobs/inf/runner.sh $t 'subsample'
sbatch -a 1-21  -c 5  -t 1440 -p 'short' -o '${o}${t}_loo-%a.out'        jobs/inf/runner.sh $t 'loo'
sbatch -a 2,3,4,5,10,11,12,13,16,18,19,20,21  -c 3  -t 1440 -p 'short' -o '${o}${t}_leaf_inf-%a.out'   jobs/inf/runner.sh $t 'leaf_inf'

sbatch -a 22-22 -c 11 -t 1440 -p 'short' -o '${o}${t}_random-%a.out'     jobs/inf/runner.sh $t 'random'
sbatch -a 22-22 -c 11 -t 1440 -p 'short' -o '${o}${t}_target-%a.out'     jobs/inf/runner.sh $t 'target'
sbatch -a 22-22 -c 11 -t 1440 -p 'short' -o '${o}${t}_input_sim-%a.out'  jobs/inf/runner.sh $t 'input_sim'
sbatch -a 22-22 -c 11 -t 1440 -p 'short' -o '${o}${t}_leaf_sim-%a.out'   jobs/inf/runner.sh $t 'leaf_sim'
sbatch -a 22-22 -c 11 -t 1440 -p 'short' -o '${o}${t}_boostin-%a.out'    jobs/inf/runner.sh $t 'boostin'
sbatch -a 22-22 -c 11 -t 1440 -p 'short' -o '${o}${t}_leaf_infSP-%a.out' jobs/inf/runner.sh $t 'leaf_infSP'
sbatch -a 22-22 -c 28 -t 1440 -p 'short' -o '${o}${t}_trex-%a.out'       jobs/inf/runner.sh $t 'trex'
sbatch -a 22-22 -c 28 -t 1440 -p 'short' -o '${o}${t}_subsample-%a.out'  jobs/inf/runner.sh $t 'subsample'
sbatch -a 22-22 -c 28 -t 1440 -p 'short' -o '${o}${t}_loo-%a.out'        jobs/inf/runner.sh $t 'loo'
