./jobs/compute_influence/primer.sh 'synthetic_regression' 'lgb' 100 7 'random'         7  60 'short'
./jobs/compute_influence/primer.sh 'synthetic_regression' 'lgb' 100 7 'boostin'        7  60 'short'
./jobs/compute_influence/primer.sh 'synthetic_regression' 'lgb' 100 7 'trex'           7  60 'short'
./jobs/compute_influence/primer.sh 'synthetic_regression' 'lgb' 100 7 'leaf_influence' 7  60 'short'
./jobs/compute_influence/primer.sh 'synthetic_regression' 'lgb' 100 7 'loo'            7  60 'short'
./jobs/compute_influence/primer.sh 'synthetic_regression' 'lgb' 100 7 'dshap'          7  60 'short'

./jobs/compute_influence/primer.sh 'synthetic_binary' 'lgb' 100 7 'random'         7  60 'short'
./jobs/compute_influence/primer.sh 'synthetic_binary' 'lgb' 100 7 'boostin'        7  60 'short'
./jobs/compute_influence/primer.sh 'synthetic_binary' 'lgb' 100 7 'trex'           7  60 'short'
./jobs/compute_influence/primer.sh 'synthetic_binary' 'lgb' 100 7 'leaf_influence' 7  60 'short'
./jobs/compute_influence/primer.sh 'synthetic_binary' 'lgb' 100 7 'loo'            7  60 'short'
./jobs/compute_influence/primer.sh 'synthetic_binary' 'lgb' 100 7 'dshap'          7  60 'short'

./jobs/compute_influence/primer.sh 'synthetic_multiclass' 'lgb' 100 7 'random'         7  60 'short'
./jobs/compute_influence/primer.sh 'synthetic_multiclass' 'lgb' 100 7 'boostin'        7  60 'short'
./jobs/compute_influence/primer.sh 'synthetic_multiclass' 'lgb' 100 7 'trex'           7  60 'short'
./jobs/compute_influence/primer.sh 'synthetic_multiclass' 'lgb' 100 7 'leaf_influence' 7  60 'short'
./jobs/compute_influence/primer.sh 'synthetic_multiclass' 'lgb' 100 7 'loo'            7  60 'short'
./jobs/compute_influence/primer.sh 'synthetic_multiclass' 'lgb' 100 7 'dshap'          7  60 'short'
