# ./jobs/roar/primer.sh 'adult' 'lgb' 200 5 'random'         3  60 'short'
# ./jobs/roar/primer.sh 'adult' 'lgb' 200 5 'boostin'        3  60 'short'
# ./jobs/roar/primer.sh 'adult' 'lgb' 200 5 'trex'           3  60 'short'
# ./jobs/roar/primer.sh 'adult' 'lgb' 200 5 'leaf_influence' 3  60 'short'
./jobs/roar/primer.sh 'adult' 'lgb' 200 5 'loo'            3  60 'short'

# ./jobs/roar/primer.sh 'bank_marketing' 'lgb' 50 5 'random'         3  60 'short'
# ./jobs/roar/primer.sh 'bank_marketing' 'lgb' 50 5 'boostin'        3  60 'short'
# ./jobs/roar/primer.sh 'bank_marketing' 'lgb' 50 5 'trex'           3  60 'short'
# ./jobs/roar/primer.sh 'bank_marketing' 'lgb' 50 5 'leaf_influence' 3  60 'short'
./jobs/roar/primer.sh 'bank_marketing' 'lgb' 50 5 'loo'            3  60 'short'

# ./jobs/roar/primer.sh 'surgical' 'lgb' 50 7 'random'         3  60 'short'
# ./jobs/roar/primer.sh 'surgical' 'lgb' 50 7 'boostin'        3  60 'short'
# ./jobs/roar/primer.sh 'surgical' 'lgb' 50 7 'trex'           3  60 'short'
./jobs/roar/primer.sh 'surgical' 'lgb' 50 7 'leaf_influence' 3  60 'short'
./jobs/roar/primer.sh 'surgical' 'lgb' 50 7 'loo'            3  60 'short'
# ./jobs/roar/primer.sh 'surgical' 'lgb' 50 7 'dshap'          3  60 'short'

# ./jobs/roar/primer.sh 'vaccine' 'lgb' 200 3 'random'         3  60 'short'
# ./jobs/roar/primer.sh 'vaccine' 'lgb' 200 3 'boostin'        3  60 'short'
# ./jobs/roar/primer.sh 'vaccine' 'lgb' 200 3 'trex'           3  60 'short'
# ./jobs/roar/primer.sh 'vaccine' 'lgb' 200 3 'leaf_influence' 3  60 'short'
./jobs/roar/primer.sh 'vaccine' 'lgb' 200 3 'loo'            3  60 'short'

# ./jobs/roar/primer.sh 'synth_binary' 'lgb' 100 7 'random'         3  60 'short'
# ./jobs/roar/primer.sh 'synth_binary' 'lgb' 100 7 'boostin'        3  60 'short'
# ./jobs/roar/primer.sh 'synth_binary' 'lgb' 100 7 'trex'           3  60 'short'
./jobs/roar/primer.sh 'synth_binary' 'lgb' 100 7 'leaf_influence' 3  60 'short'
./jobs/roar/primer.sh 'synth_binary' 'lgb' 100 7 'loo'            3  60 'short'

# ./jobs/roar/primer.sh 'synth_regression' 'lgb' 10 2 'random'         3  60 'short'
# ./jobs/roar/primer.sh 'synth_regression' 'lgb' 10 2 'boostin'        3  60 'short'
# ./jobs/roar/primer.sh 'synth_regression' 'lgb' 10 2 'trex'           3  60 'short'
# ./jobs/roar/primer.sh 'synth_regression' 'lgb' 10 2 'leaf_influence' 3  60 'short'
./jobs/roar/primer.sh 'synth_regression' 'lgb' 10 2 'loo'            3  60 'short'

# ./jobs/roar/primer.sh 'synth_multiclass' 'lgb' 200 7 'random'         3  60 'short'
# ./jobs/roar/primer.sh 'synth_multiclass' 'lgb' 200 7 'boostin'        3  60 'short'
# ./jobs/roar/primer.sh 'synth_multiclass' 'lgb' 200 7 'trex'           3  60 'short'
# ./jobs/roar/primer.sh 'synth_multiclass' 'lgb' 200 7 'leaf_influence' 3  60 'short'
./jobs/roar/primer.sh 'synth_multiclass' 'lgb' 200 7 'loo'            3  60 'short'
